image:
  - Visual Studio 2017
clone_folder: c:\repo\source
build_script:
- cmd: >-
    mkdir build

    cd build

    cmake c:\repo\source -G "Visual Studio 15"

    cmake --build . --config "Debug"

test_script:
- cmd: Debug\blake.exe

